# Generated by Django 4.2.16 on 2024-10-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('coste', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartaPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('salud_max', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenadorPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entrenador', to='Core.jugadorentrenador')),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.cartapokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.ataque')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_entrenador', to='Core.jugadorentrenador')),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.cartapokemon')),
            ],
        ),
        migrations.CreateModel(
            name='CartaPokemonAtaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.ataque')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartapokemon')),
            ],
        ),
    ]
