# Generated by Django 4.2.16 on 2024-10-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='ataque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartapokemonataque'),
        ),
        migrations.DeleteModel(
            name='EntrenadorPokemon',
        ),
    ]
