# Generated by Django 4.2.16 on 2024-10-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_rename_nombre_cartapokemon_nombre_pokemon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadorentrenador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='jugadorentrenador',
            name='mail',
        ),
    ]
