# Generated by Django 4.2.16 on 2024-10-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_jugadorentrenador_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartapokemon',
            name='apodo',
        ),
    ]
