# Generated by Django 4.2.16 on 2024-10-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_coleccion_ataque_coleccion_ataque1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazo_entrenador', to='Core.jugadorentrenador')),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.coleccion')),
            ],
        ),
    ]
