# Generated by Django 4.2.16 on 2024-10-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_mazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazo',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cartapokemonataque',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_aprendibles', to='Core.cartapokemon'),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_coleccionados', to='Core.cartapokemon'),
        ),
        migrations.AlterField(
            model_name='mazo',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazo_del_entrenador', to='Core.jugadorentrenador'),
        ),
        migrations.AlterField(
            model_name='mazo',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_del_mazo', to='Core.coleccion'),
        ),
    ]
