# Generated by Django 4.2.16 on 2024-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_mazo_nombre_alter_cartapokemonataque_pokemon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mazo',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='mazo',
            name='pokemon',
            field=models.ManyToManyField(related_name='pokemons_del_mazo', to='Core.coleccion'),
        ),
    ]
