# Generated by Django 4.2.16 on 2024-10-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_rename_nombre_mazo_mote_mazo_alter_mazo_entrenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazo',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_del_mazo', to='Core.coleccion'),
        ),
    ]
