# Generated by Django 4.2.16 on 2024-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_mazo_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mazo',
            old_name='mote_mazo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='mazo',
            name='entrenador',
        ),
        migrations.RemoveField(
            model_name='mazo',
            name='pokemon',
        ),
        migrations.CreateModel(
            name='MazoEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenador_mazo', to='Core.jugadorentrenador')),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_mazo', to='Core.mazo')),
            ],
            options={
                'unique_together': {('nombre', 'entrenador')},
            },
        ),
        migrations.CreateModel(
            name='MazoCartaPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mazo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenador_mazo', to='Core.mazoentrenador')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_mazo', to='Core.coleccion')),
            ],
        ),
    ]
