# Generated by Django 4.2.16 on 2024-10-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_mote_mazo_mazo_nombre_remove_mazo_entrenador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MazoCartaPokemon',
            new_name='MazoColeccion',
        ),
    ]
