# Generated by Django 4.2.16 on 2024-10-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_rename_mazocartapokemon_mazocoleccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mazoentrenador',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mazoentrenador',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mazoentrenador',
            unique_together={('entrenador', 'nombre')},
        ),
        migrations.DeleteModel(
            name='Mazo',
        ),
    ]
