# Generated by Django 4.2.16 on 2024-10-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_mazoentrenador_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mazoentrenador',
            old_name='nombre',
            new_name='nombre_mazo',
        ),
        migrations.AlterUniqueTogether(
            name='mazocoleccion',
            unique_together={('mazo', 'pokemon')},
        ),
        migrations.AlterUniqueTogether(
            name='mazoentrenador',
            unique_together={('entrenador', 'nombre_mazo')},
        ),
    ]
