# Generated by Django 4.2.16 on 2024-10-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_rename_nombre_mazoentrenador_nombre_mazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaMazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartapokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mazo', models.CharField(max_length=50)),
                ('cartas', models.ManyToManyField(through='Core.CartaMazo', to='Core.cartapokemon')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.jugadorentrenador')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mazoentrenador',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mazoentrenador',
            name='entrenador',
        ),
        migrations.DeleteModel(
            name='MazoColeccion',
        ),
        migrations.DeleteModel(
            name='MazoEntrenador',
        ),
        migrations.AddField(
            model_name='cartamazo',
            name='mazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.mazo'),
        ),
    ]
