# Generated by Django 5.1.1 on 2024-10-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_remove_mazo_cartas_alter_cartamazo_carta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cartapokemon',
            name='rare',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BoosterPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_del_sobre', to='Core.set')),
            ],
        ),
        migrations.AddField(
            model_name='cartapokemon',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_de_la_carta', to='Core.set'),
        ),
    ]
