# Generated by Django 4.2.16 on 2024-10-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0018_remove_mazo_cartas_alter_cartamazo_carta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionTurnoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(blank=True, choices=[('1', 'Ataque'), ('2', 'Pasar turno'), ('3', 'Recarga energía'), ('4', 'Jugar carta')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorBatalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.jugadorentrenador')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.mazo')),
            ],
            options={
                'unique_together': {('batalla', 'jugador'), ('jugador', 'mazo')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField(default=1)),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaTurnoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turno')),
            ],
        ),
        migrations.CreateModel(
            name='ManoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turno')),
            ],
        ),
        migrations.CreateModel(
            name='DescartesJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turno')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia', models.PositiveIntegerField(default=0)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turno')),
            ],
            options={
                'unique_together': {('turno', 'jugador')},
            },
        ),
    ]
