# Generated by Django 4.2.16 on 2024-10-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_alter_coleccion_pokemon'),
        ('Battle', '0005_remove_turnojugador_activo_turnojugador_batalla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnojugador',
            old_name='jugador',
            new_name='jugadorbatalla',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='turnojugador',
            unique_together={('turno', 'jugadorbatalla')},
        ),
        migrations.AddField(
            model_name='accionturnojugador',
            name='batalla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla'),
        ),
        migrations.AddField(
            model_name='accionturnojugador',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla'),
        ),
        migrations.AddField(
            model_name='accionturnojugador',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Battle.turnojugador'),
        ),
        migrations.AddField(
            model_name='jugadorbatalla',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batalla',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartaactivajugador',
            name='carta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo'),
        ),
        migrations.AlterField(
            model_name='descartesjugador',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turnojugador'),
        ),
        migrations.AlterField(
            model_name='manojugador',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turnojugador'),
        ),
        migrations.AlterField(
            model_name='reservajugador',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turnojugador'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cartareservajugador',
            unique_together={('reserva', 'carta')},
        ),
        migrations.CreateModel(
            name='MazoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.batalla')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.jugadorbatalla')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.turnojugador')),
            ],
        ),
        migrations.CreateModel(
            name='ContadoresSaludCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadores', models.PositiveIntegerField(default=0)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
            ],
        ),
        migrations.CreateModel(
            name='CartaMazoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cartamazo')),
                ('mazojugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battle.mazojugador')),
            ],
        ),
        migrations.RemoveField(
            model_name='turnojugador',
            name='batalla',
        ),
    ]
